apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-boardgame
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boardgame
  template:
    metadata:
      labels:
        app: boardgame
    spec:
      serviceAccountName: jenkins-service-account
      containers:
        - name: boardgame
          image: ECR_REGISTRY/ECR_REPO:BUILD_ID
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0d4abre94fa4fe1e6"
spec:
  selector:
    app: boardgame
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
